import * as fs from 'fs';
import * as path from 'path';
import * as dotenv from 'dotenv';

// Load environment variables locally
dotenv.config({ path: path.join(process.cwd(), '.env.local') });

const MIGRATIONS_DIR = path.join(process.cwd(), 'libs', 'db', 'src', 'supabase', 'migrations');
const TARGET_API_DIR = path.join(process.cwd(), 'apps', 'nextblock', 'app', 'api', 'cron', 'reset-sandbox');
const OUT_FILE = path.join(TARGET_API_DIR, 'sandboxResetSql.ts');

async function generateSandboxReset() {
  console.log('[generate-sandbox-reset] Starting compilation...');
  if (!fs.existsSync(MIGRATIONS_DIR)) {
    console.error(`Directory not found: ${MIGRATIONS_DIR}`);
    process.exit(1);
  }

  // 1. Read and filter migration files
  const files = fs.readdirSync(MIGRATIONS_DIR)
    .filter(f => f.endsWith('.sql'))
    .filter(f => !f.toLowerCase().includes('sandbox')) // Exclude sandbox-specific files
    .filter(f => f !== '99999999999999_auto_sandbox_reset.sql')
    .sort();

  // Refuse to bake a badly named file into the reset payload (GGNNN scheme; see
  // tools/scripts/lib/migration-naming.js and docs/04).
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const { validateMigrationNames } = require('./lib/migration-naming.js');
  const naming = validateMigrationNames(files);
  if (naming.errors.length > 0) {
    console.error('[generate-sandbox-reset] migration file names violate the GGNNN scheme:');
    naming.errors.forEach((error: string) => console.error(`  - ${error}`));
    process.exit(1);
  }

  console.log(`[generate-sandbox-reset] Found ${files.length} standard migrations (generation ${naming.generation}).`);

  let concatenatedSql = '';
  for (const file of files) {
    console.log(` - Reading ${file}`);
    // Normalise to LF so the output does not depend on the checkout's line endings
    // (core.autocrlf), and so the BEGIN/COMMIT stripping below sees consistent input.
    let content = fs.readFileSync(path.join(MIGRATIONS_DIR, file), 'utf-8').replace(/\r\n/g, '\n');
    // Strip BEGIN; and COMMIT; because they cause errors inside an EXECUTE block
    content = content.replace(/(?:^|\n)\s*BEGIN\s*;/ig, '\n');
    content = content.replace(/(?:^|\n)\s*COMMIT\s*;/ig, '\n');
    concatenatedSql += `\n\n-- >>> FROM: ${file} <<<\n`;
    concatenatedSql += content;
  }

  // Record every applied migration in history. The reset truncates
  // supabase_migrations.schema_migrations above; without re-recording it, the CLI
  // (`npm run db:migrate:check`) would see every baseline file as pending on the sandbox.
  const migrationHistoryValues = files
    .map((file) => {
      const version = file.split('_')[0];
      const name = file.slice(version.length + 1).replace(/\.sql$/, '').replace(/'/g, "''");
      return `    ('${version}', '${name}')`;
    })
    .join(',\n');

  // 2. Build the Raw Script String
  const procedureSql = `-- AUTO-GENERATED: Sandbox Reset Script. Do Not Edit Manually.
-- Generated by tools/scripts/generate-sandbox-reset.ts

  -- Step A: Erase all non-demo users
  DELETE FROM auth.users
  WHERE id NOT IN (
    '63a8aa07-ef6e-4cc7-bafa-ece023c74366'::uuid,
    'e3a2c121-70a4-4239-a9df-f70ce717f5a1'::uuid
  );

  -- Step B0: Refuse to cascade into an extension that is registered in schema public.
  -- DROP SCHEMA public CASCADE drops every extension whose extnamespace is public, and for
  -- pg_net that deadlocks the reset: the pg_net worker holds a lock on net.http_request_queue
  -- for as long as the HTTP request that triggered this very reset is outstanding, so the
  -- DROP waits on the worker, the worker waits on the route, and Vercel kills the function
  -- at maxDuration (a 504 on every run). Relocatable extensions are moved to "extensions";
  -- anything else fails loudly here instead of hanging (npm run sandbox:schedule reinstalls
  -- pg_net WITH SCHEMA extensions).
  DO $nb_ext_guard$
  DECLARE r record;
  BEGIN
    FOR r IN
      SELECT extname, extrelocatable
        FROM pg_extension
       WHERE extnamespace = 'public'::regnamespace
    LOOP
      IF r.extrelocatable AND to_regnamespace('extensions') IS NOT NULL THEN
        RAISE NOTICE 'sandbox reset: moving extension % out of schema public', r.extname;
        EXECUTE format('ALTER EXTENSION %I SET SCHEMA extensions', r.extname);
      ELSE
        RAISE EXCEPTION 'sandbox reset aborted: extension % is installed in schema public and DROP SCHEMA public CASCADE would drop it. Reinstall it WITH SCHEMA extensions (for pg_net: npm run sandbox:schedule -- https://cms.nextblock.dev).', r.extname;
      END IF;
    END LOOP;
  END $nb_ext_guard$;

  -- Step B: Wipe public schema and truncate migrations
  DROP SCHEMA public CASCADE;
  CREATE SCHEMA public;

  -- Restore default public schema privileges so the standard migrations succeed
  GRANT USAGE ON SCHEMA public TO postgres, anon, authenticated, service_role;
  GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO postgres, anon, authenticated, service_role;
  GRANT ALL PRIVILEGES ON ALL ROUTINES IN SCHEMA public TO postgres, anon, authenticated, service_role;
  GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO postgres, anon, authenticated, service_role;
  ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO postgres, anon, authenticated, service_role;
  ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO postgres, anon, authenticated, service_role;
  ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres, anon, authenticated, service_role;

  TRUNCATE TABLE supabase_migrations.schema_migrations;

  -- Step C: Execute full schema & seed from production migrations
${concatenatedSql}

  -- Step C2: Take the API roles' EXECUTE back off every trigger function. Step B's
  -- DEFAULT PRIVILEGES hand anon/authenticated EXECUTE on each function the migrations
  -- create; trigger functions never need it (EXECUTE is only checked at CREATE TRIGGER
  -- time and PostgREST cannot call them), and the Security Advisor flags the SECURITY
  -- DEFINER ones. Same pass as lib/setup/schema-apply.ts runs after a build-time apply.
  do $nb_trg$
  declare r record;
  begin
    for r in
      select p.oid::regprocedure as sig
        from pg_proc p
        join pg_type t on t.oid = p.prorettype
       where p.pronamespace = 'public'::regnamespace and t.typname = 'trigger'
    loop
      execute format('revoke execute on function %s from public, anon, authenticated', r.sig);
    end loop;
  end $nb_trg$;

  -- Step D: Record the applied migrations in history (truncated in Step B) so
  -- \`npm run db:migrate:check\` reports up to date instead of listing every file as pending.
  INSERT INTO supabase_migrations.schema_migrations (version, name) VALUES
${migrationHistoryValues}
  ON CONFLICT (version) DO NOTHING;

  -- Step E: Anchor preserved profiles
  INSERT INTO public.profiles (id, updated_at, full_name, avatar_url, website, role)
  SELECT preserved_user.id, NULL, NULL, NULL, NULL, 'ADMIN'
  FROM (
    VALUES
      ('63a8aa07-ef6e-4cc7-bafa-ece023c74366'::uuid),
      ('e3a2c121-70a4-4239-a9df-f70ce717f5a1'::uuid)
  ) AS preserved_user(id)
  WHERE EXISTS (SELECT 1 FROM auth.users WHERE id = preserved_user.id)
    AND NOT EXISTS (SELECT 1 FROM public.profiles WHERE id = preserved_user.id);

  -- Step F: Re-assert the "first admin exists" flag. The sandbox preserves its demo
  -- ADMIN users across the wipe (Steps A & E), but the reseeded baseline resets
  -- is_admin_created to 'false' and handle_new_user() only flips it on a NEW auth.users
  -- INSERT -- which never fires for preserved users. Without this the proxy setup-gate
  -- funnels ALL sandbox traffic (including this reset cron on its next run) to /setup even
  -- though admins already exist. Guarded on an ADMIN profile actually being present.
  UPDATE public.site_settings
  SET value = 'true'::jsonb
  WHERE key = 'is_admin_created'
    AND EXISTS (SELECT 1 FROM public.profiles WHERE role = 'ADMIN'::public.user_role);
`;

  if (!fs.existsSync(TARGET_API_DIR)) {
    fs.mkdirSync(TARGET_API_DIR, { recursive: true });
  }

  // 3. Export as a typescript variable into the route directory
  const tsContent = `// AUTO-GENERATED FILE. Do not edit this file directly.
// Regenerate it from repo root with: npm run generate:sandbox
// Source of truth: tools/scripts/generate-sandbox-reset.ts and libs/db/src/supabase/migrations/*.sql

export const SANDBOX_RESET_SQL = \`\n${procedureSql.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')}\n\`;\n`;
  fs.writeFileSync(OUT_FILE, tsContent);
  
  console.log(`[generate-sandbox-reset] ✅ Successfully compiled Sandbox Reset SQL to ${OUT_FILE}`);
}

generateSandboxReset();
