"use client";

import { useMemo } from "react";
import { ThemeProvider } from "next-themes";

// Suppress the React 19 warning for the <script> tag generated by next-themes in development
if (typeof window !== 'undefined' && process.env.NODE_ENV === 'development') {
  const orig = console.error;
  console.error = (...args: any[]) => {
    if (typeof args[0] === 'string' && args[0].includes('Encountered a script tag')) {
      return;
    }
    orig.apply(console, args);
  };
}
import { AuthProvider } from '../context/AuthContext';
import { LanguageProvider, useLanguage } from '../context/LanguageContext';
import { CurrentContentProvider } from '../context/CurrentContentContext';
import { ThemeCatalogProvider } from '../context/ThemeCatalogContext';
import { DeferredCartTranslator } from '../components/DeferredCartTranslator';
import { CurrencyProvider } from '@nextblock-cms/ecommerce/CurrencyProvider';
import { TranslationsProvider } from '@nextblock-cms/utils';
import {
  expandCompactTranslations,
  isCompactTranslations,
  type ClientTranslationRow,
  type CompactTranslations,
} from '../lib/i18n/slim-translations';

function TranslationBridge({
  children,
  translations,
}: {
  children: React.ReactNode;
  /** Compact `[key, value]` tuples from the layout (see lib/i18n/slim-translations.ts); the
   *  row shape is still accepted so older callers and tests keep working. */
  translations: CompactTranslations | ClientTranslationRow[];
}) {
  const { currentLocale } = useLanguage();
  const rows = useMemo(
    () => (isCompactTranslations(translations) ? expandCompactTranslations(translations) : translations),
    [translations],
  );

  return (
    <TranslationsProvider translations={rows} lang={currentLocale}>
      {children}
    </TranslationsProvider>
  );
}

export function Providers({ children, ...props }: { children: React.ReactNode;[key: string]: any; }) {
  const {
    serverUser,
    serverProfile,
    serverLocale,
    initialCurrencies,
    initialCurrencyCode,
    initialAvailableLanguages,
    initialDefaultLanguage,
    rememberVisitorChoice,
    translations,
    nonce,
    themeSlugs,
    initialTheme,
    themeCatalog,
  } = props;

  // Themes come from the site_themes table. Fall back to the three that ship in
  // libs/ui/src/styles/theme.css if the table is empty or unreachable, so the
  // switcher never renders an empty list.
  const resolvedThemes: string[] =
    Array.isArray(themeSlugs) && themeSlugs.length > 0 ? themeSlugs : ['light', 'dark', 'vibrant'];
  const resolvedDefault: string =
    typeof initialTheme === 'string' && resolvedThemes.includes(initialTheme) ? initialTheme : 'light';

  return (
    <AuthProvider serverUser={serverUser} serverProfile={serverProfile}>
      <LanguageProvider
        serverLocale={serverLocale}
        initialAvailableLanguages={initialAvailableLanguages}
        initialDefaultLanguage={initialDefaultLanguage}
        rememberVisitorChoice={rememberVisitorChoice}
      >
        <CurrencyProvider
          initialCurrencies={initialCurrencies}
          initialCurrencyCode={initialCurrencyCode}
          locale={serverLocale}
        >
          <CurrentContentProvider>
            <DeferredCartTranslator />
            <TranslationBridge translations={translations}>
              <ThemeProvider
                attribute="class"
                defaultTheme={resolvedDefault}
                enableSystem
                disableTransitionOnChange
                nonce={nonce}
                themes={resolvedThemes}
              >
                <ThemeCatalogProvider themes={themeCatalog}>{children}</ThemeCatalogProvider>
              </ThemeProvider>
            </TranslationBridge>
          </CurrentContentProvider>
        </CurrencyProvider>
      </LanguageProvider>
    </AuthProvider>
  );
}
