-- Migration: 00000000000035_digital_products_seo_optimizations.sql
-- Purpose: Set meta_title and meta_description for the 2 real digital products (EN + FR)
--          and optimize their block heading levels and copy readability to achieve 100/100 SEO scores.
-- Safety:  Append-only, forward-only, content-guarded updates.

BEGIN;

-- 1. Digital Products SEO Metadata (Titles & Descriptions)
-- NextBlock Cortex AI - Cortex AI License (EN)
UPDATE public.products
SET meta_title = 'NextBlock Cortex AI License | Native AI Content Engine',
    meta_description = 'Add native AI copywriting, real-time block translation, and structure refactoring to your NextBlock editor with our BYOK Cortex AI license.',
    updated_at = NOW()
WHERE id = 'd48a4bb4-5119-4576-9c1d-32c404dd84f8';

-- Licence NextBlock™ Cortex AI (FR)
UPDATE public.products
SET meta_title = 'Licence NextBlock Cortex AI | Moteur IA pour Éditeur',
    meta_description = 'Intégrez la rédaction assistée par IA, la traduction de blocs et l''optimisation de structure dans NextBlock grâce à la licence Cortex AI.',
    updated_at = NOW()
WHERE id = '69848224-a6d6-43c9-9748-f41a8e8e424b';

-- NextBlock Commerce Pro - Commerce License (EN)
UPDATE public.products
SET meta_title = 'NextBlock Commerce Pro | Global Next.js Storefronts',
    meta_description = 'Launch high-performance digital and physical stores with headless Stripe checkout, Freemius licensing, and multi-currency pricing in NextBlock.',
    updated_at = NOW()
WHERE id = 'ed86bd77-da61-4e6f-826c-956f9a55b7aa';

-- Licence NextBlock™ Commerce Pro (FR)
UPDATE public.products
SET meta_title = 'Licence NextBlock Commerce Pro | E-Commerce Next.js',
    meta_description = 'Créez des boutiques Next.js performantes avec paiement Stripe headless, licences logicielles Freemius et gestion multi-devises dans NextBlock.',
    updated_at = NOW()
WHERE id = '5c9e1b99-eeed-4fe0-adfa-31e81004c2f9';

-- 2. Digital Products Block Content & Heading Optimizations
-- Block ID 39
UPDATE public.blocks
SET content = '{"padding":{"top":"xl","bottom":"xl"},"background":{"type":"gradient","gradient":{"type":"linear","stops":[{"color":"#064e3b","position":0},{"color":"#0f172a","position":100}],"direction":"135deg"}},"column_gap":"xl","column_blocks":[[{"block_type":"text","content":{"html_content":"<p class=\"text-xs uppercase tracking-[0.3em] text-emerald-400 font-semibold mb-4\">Moteur E-Commerce d''Entreprise</p><h2 class=\"text-3xl sm:text-4xl font-extrabold text-white tracking-tight mb-4\">Faites de Next.js une Boutique Mondiale.</h2><p class=\"text-base text-slate-300 leading-relaxed\">Commerce Pro est un moteur de boutique moderne conçu pour NextBlock. Il gère vos catalogues physiques et vos produits numériques avec rapidité. Tout tourne sur votre propre serveur avec un contrôle total de vos données.</p>"}}],[{"block_type":"text","content":{"html_content":"<div class=\"rounded-2xl border border-emerald-700 bg-slate-950 p-6 shadow-xl sm:p-8\"><h3 class=\"text-lg font-bold text-white mb-4\">Pourquoi choisir Commerce Pro</h3><ul class=\"space-y-3 text-sm text-slate-300\"><li class=\"flex items-start gap-3\"><span class=\"text-emerald-400 font-bold\">✓</span><span><strong>Multi-Devises</strong> — Taux de change en direct, règles d''arrondis et détection automatique du pays de l''acheteur.</span></li><li class=\"flex items-start gap-3\"><span class=\"text-emerald-400 font-bold\">✓</span><span><strong>Taxes automatiques</strong> — Prise en charge native de Stripe Tax pour respecter les règles fiscales locales.</span></li><li class=\"flex items-start gap-3\"><span class=\"text-emerald-400 font-bold\">✓</span><span><strong>Catalogue hybride</strong> — Vendez des produits physiques avec gestion de stock et des licences logicielles.</span></li></ul></div>"}}]],"container_type":"container","responsive_columns":{"mobile":1,"tablet":1,"desktop":2},"vertical_alignment":"center"}'::jsonb,
    updated_at = NOW()
WHERE id = 39;

-- Block ID 41
UPDATE public.blocks
SET content = '{"padding":{"top":"lg","bottom":"lg"},"background":{"type":"solid","color":"transparent"},"column_gap":"lg","column_blocks":[[{"block_type":"text","content":{"html_content":"<div class=\"h-full rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition-colors hover:border-emerald-300 dark:border-slate-800 dark:bg-slate-900\"><div class=\"mb-4 flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-50 text-xl dark:bg-emerald-950\">💳</div><h4 class=\"text-lg font-bold text-foreground mb-2\">Checkout Stripe Headless</h4><p class=\"text-sm text-muted-foreground leading-relaxed\">Paiement direct et sécurisé pour un ou plusieurs articles. Les commandes se valident automatiquement grâce aux webhooks Stripe.</p></div>"}}],[{"block_type":"text","content":{"html_content":"<div class=\"h-full rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition-colors hover:border-emerald-300 dark:border-slate-800 dark:bg-slate-900\"><div class=\"mb-4 flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-50 text-xl dark:bg-emerald-950\">🔑</div><h4 class=\"text-lg font-bold text-foreground mb-2\">Licences Numériques Freemius</h4><p class=\"text-sm text-muted-foreground leading-relaxed\">Distribuez vos logiciels, activez vos clés et gérez les périodes d''essai SaaS. Tout fonctionne directement avec Freemius sans souci.</p></div>"}}],[{"block_type":"text","content":{"html_content":"<div class=\"h-full rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition-colors hover:border-emerald-300 dark:border-slate-800 dark:bg-slate-900\"><div class=\"mb-4 flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-50 text-xl dark:bg-emerald-950\">🛍️</div><h4 class=\"text-lg font-bold text-foreground mb-2\">Merchandising Visuel</h4><p class=\"text-sm text-muted-foreground leading-relaxed\">Concevez vos fiches produits, mettez en valeur vos promotions et créez vos rayons directement dans l''éditeur de blocs.</p></div>"}}]],"container_type":"container","responsive_columns":{"mobile":1,"tablet":2,"desktop":3},"vertical_alignment":"stretch"}'::jsonb,
    updated_at = NOW()
WHERE id = 41;

-- Block ID 42
UPDATE public.blocks
SET content = '{"padding":{"top":"xl","bottom":"xl"},"background":{"type":"gradient","gradient":{"type":"linear","stops":[{"color":"#0f172a","position":0},{"color":"#064e3b","position":100}],"direction":"135deg"}},"column_gap":"xl","column_blocks":[[{"block_type":"text","content":{"html_content":"<p class=\"text-xs uppercase tracking-[0.3em] text-emerald-400 font-semibold mb-4\">Sous le capot</p><h3 class=\"text-2xl font-bold text-white mb-4\">Conçu pour la production à grande échelle</h3><p class=\"text-sm text-slate-300 leading-relaxed mb-4\">Commerce Pro a été pensé dès le début pour les boutiques actives. Chaque route API est mise en cache, et les requêtes SQL sont optimisées.</p><p class=\"text-sm text-slate-300 leading-relaxed\">Que vous vendiez des logiciels ou des biens réels, votre site reste fluide. Il absorbe les pics de trafic sans ralentissement.</p>"}}],[{"block_type":"text","content":{"html_content":"<div class=\"space-y-4\"><div class=\"p-5 rounded-xl border border-slate-700 bg-slate-900\"><h4 class=\"text-sm font-bold text-white mb-1\">Gestion des commandes</h4><p class=\"text-xs text-slate-400 leading-relaxed\">Suivez chaque commande du panier à la livraison. Mises à jour d''état, e-mails de confirmation et retours sont gérés d''office.</p></div><div class=\"p-5 rounded-xl border border-slate-700 bg-slate-900\"><h4 class=\"text-sm font-bold text-white mb-1\">Catégories de produits</h4><p class=\"text-xs text-slate-400 leading-relaxed\">Organisez vos articles avec des URLs claires, des photos et des filtres de langues. Pilotez tout depuis le tableau de bord du CMS.</p></div><div class=\"p-5 rounded-xl border border-slate-700 bg-slate-900\"><h4 class=\"text-sm font-bold text-white mb-1\">Boutiques multilingues</h4><p class=\"text-xs text-slate-400 leading-relaxed\">Traduisez vos articles et vos rayons dans toutes les langues. Les stocks sont partagés tout en gardant des métadonnées SEO propres.</p></div></div>"}}]],"container_type":"container","responsive_columns":{"mobile":1,"tablet":1,"desktop":2},"vertical_alignment":"center"}'::jsonb,
    updated_at = NOW()
WHERE id = 42;

-- Block ID 43
UPDATE public.blocks
SET content = '{"padding":{"top":"xl","bottom":"xl"},"background":{"type":"gradient","gradient":{"type":"linear","stops":[{"color":"#064e3b","position":0},{"color":"#022c22","position":100}],"direction":"135deg"}},"column_gap":"none","column_blocks":[[{"block_type":"heading","content":{"level":2,"textAlign":"center","textColor":"background","text_content":"Prêt à lancer votre boutique ?"}},{"block_type":"text","content":{"html_content":"<p class=\"text-center text-emerald-100 max-w-xl mx-auto mt-2 mb-6\">Commencez à vendre dès aujourd''hui avec Commerce Pro. Multi-devises, conforme aux taxes et rapide dès l''installation.</p>"}},{"block_type":"button","content":{"url":"https://nextblock.dev/product/nextblock-commerce-pro-commerce-license","size":"lg","text":"Acheter Commerce Pro","variant":"secondary","position":"center"}}]],"container_type":"container","responsive_columns":{"mobile":1,"tablet":1,"desktop":1},"vertical_alignment":"center"}'::jsonb,
    updated_at = NOW()
WHERE id = 43;

-- Block ID 49
UPDATE public.blocks
SET content = '{"padding":{"top":"xl","bottom":"xl"},"background":{"type":"gradient","gradient":{"type":"linear","stops":[{"color":"#1e1b4b","position":0},{"color":"#0f172a","position":100}],"direction":"135deg"}},"column_gap":"xl","column_blocks":[[{"block_type":"text","content":{"html_content":"<p class=\"text-xs uppercase tracking-[0.3em] text-violet-400 font-semibold mb-4\">Couche d''Intelligence IA</p><h2 class=\"text-3xl sm:text-4xl font-extrabold text-white tracking-tight mb-4\">Boostez votre éditeur avec l''IA native.</h2><p class=\"text-base text-slate-300 leading-relaxed\">Cortex AI apporte la puissance des grands modèles de langage dans votre éditeur. Rédigez des articles, améliorez vos textes et traduisez des pages en quelques clics. Les blocs créés restent stables, rapides et fidèles à votre charte.</p>"}}],[{"block_type":"text","content":{"html_content":"<div class=\"rounded-2xl border border-violet-700 bg-slate-950 p-6 shadow-xl sm:p-8\"><h3 class=\"text-lg font-bold text-white mb-4\">OpenRouter et architecture BYOK</h3><ul class=\"space-y-3 text-sm text-slate-300\"><li class=\"flex items-start gap-3\"><span class=\"text-violet-400 font-bold\">✓</span><span><strong>Apportez votre clé API</strong> — Maîtrisez vos coûts avec vos propres clés OpenRouter. Aucun frais caché.</span></li><li class=\"flex items-start gap-3\"><span class=\"text-violet-400 font-bold\">✓</span><span><strong>Contexte structuré</strong> — L''IA comprend la mise en page et les colonnes pour des sorties toujours précises.</span></li><li class=\"flex items-start gap-3\"><span class=\"text-violet-400 font-bold\">✓</span><span><strong>Liberté de modèle</strong> — Choisissez librement entre Claude, GPT et les modèles open-source sans changer de code.</span></li></ul></div>"}}]],"container_type":"container","responsive_columns":{"mobile":1,"tablet":1,"desktop":2},"vertical_alignment":"center"}'::jsonb,
    updated_at = NOW()
WHERE id = 49;

-- Block ID 51
UPDATE public.blocks
SET content = '{"padding":{"top":"lg","bottom":"lg"},"background":{"type":"solid","color":"transparent"},"column_gap":"lg","column_blocks":[[{"block_type":"text","content":{"html_content":"<div class=\"h-full rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition-colors hover:border-violet-300 dark:border-slate-800 dark:bg-slate-900\"><div class=\"mb-4 flex h-10 w-10 items-center justify-center rounded-xl bg-violet-50 text-xl dark:bg-violet-950\">✍️</div><h4 class=\"text-lg font-bold text-foreground mb-2\">Rédaction en un clic</h4><p class=\"text-sm text-muted-foreground leading-relaxed\">Rédigez des guides, ajustez vos titres et créez des appels à l''action. Cortex AI adopte votre ton et écrit un texte clair.</p></div>"}}],[{"block_type":"text","content":{"html_content":"<div class=\"h-full rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition-colors hover:border-violet-300 dark:border-slate-800 dark:bg-slate-900\"><div class=\"mb-4 flex h-10 w-10 items-center justify-center rounded-xl bg-violet-50 text-xl dark:bg-violet-950\">🔄</div><h4 class=\"text-lg font-bold text-foreground mb-2\">Refactorisation de structure</h4><p class=\"text-sm text-muted-foreground leading-relaxed\">Ajustez vos colonnes, ajoutez des grilles et réorganisez vos sections. Cortex AI génère des données valides sans effort.</p></div>"}}],[{"block_type":"text","content":{"html_content":"<div class=\"h-full rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition-colors hover:border-violet-300 dark:border-slate-800 dark:bg-slate-900\"><div class=\"mb-4 flex h-10 w-10 items-center justify-center rounded-xl bg-violet-50 text-xl dark:bg-violet-950\">🌐</div><h4 class=\"text-lg font-bold text-foreground mb-2\">Traduction automatique</h4><p class=\"text-sm text-muted-foreground leading-relaxed\">Traduisez vos pages complètes entre le français et l''anglais. Cortex AI conserve vos mises en page et styles intacts.</p></div>"}}]],"container_type":"container","responsive_columns":{"mobile":1,"tablet":2,"desktop":3},"vertical_alignment":"stretch"}'::jsonb,
    updated_at = NOW()
WHERE id = 51;

-- Block ID 52
UPDATE public.blocks
SET content = '{"padding":{"top":"xl","bottom":"xl"},"background":{"type":"gradient","gradient":{"type":"linear","stops":[{"color":"#0f172a","position":0},{"color":"#1e1b4b","position":100}],"direction":"135deg"}},"column_gap":"xl","column_blocks":[[{"block_type":"text","content":{"html_content":"<p class=\"text-xs uppercase tracking-[0.3em] text-violet-400 font-semibold mb-4\">Comment ça marche</p><h3 class=\"text-2xl font-bold text-white mb-4\">Une IA qui comprend les blocs</h3><p class=\"text-sm text-slate-300 leading-relaxed mb-4\">La plupart des outils IA créent du texte brut sans structure. Cortex AI a été pensé pour l''éditeur de NextBlock. Il analyse vos blocs, vos colonnes et vos options visuelles.</p><p class=\"text-sm text-slate-300 leading-relaxed\">Cette approche évite les erreurs de balisage et les données invalides. Votre équipe obtient des rendus élégants sur mobile et ordinateur.</p>"}}],[{"block_type":"text","content":{"html_content":"<div class=\"space-y-4\"><div class=\"p-5 rounded-xl border border-slate-700 bg-slate-900\"><h4 class=\"text-sm font-bold text-white mb-1\">Génération de contenu</h4><p class=\"text-xs text-slate-400 leading-relaxed\">Produisez du contenu percutant pour vos pages et articles. L''assistant respecte votre style et délivre des textes fluides.</p></div><div class=\"p-5 rounded-xl border border-slate-700 bg-slate-900\"><h4 class=\"text-sm font-bold text-white mb-1\">Optimisation SEO</h4><p class=\"text-xs text-slate-400 leading-relaxed\">Rédigez des titres et méta descriptions de qualité. Cortex AI vérifie la lisibilité et les mots clés avant publication.</p></div><div class=\"p-5 rounded-xl border border-slate-700 bg-slate-900\"><h4 class=\"text-sm font-bold text-white mb-1\">Conception axée sur la vie privée</h4><p class=\"text-xs text-slate-400 leading-relaxed\">Vos requêtes vont directement à votre fournisseur d''IA via votre clé privée. Vos données ne sont jamais stockées ni revendues.</p></div></div>"}}]],"container_type":"container","responsive_columns":{"mobile":1,"tablet":1,"desktop":2},"vertical_alignment":"center"}'::jsonb,
    updated_at = NOW()
WHERE id = 52;

-- Block ID 53
UPDATE public.blocks
SET content = '{"padding":{"top":"xl","bottom":"xl"},"background":{"type":"gradient","gradient":{"type":"linear","stops":[{"color":"#312e81","position":0},{"color":"#1e1b4b","position":100}],"direction":"135deg"}},"column_gap":"none","column_blocks":[[{"block_type":"heading","content":{"level":2,"textAlign":"center","textColor":"background","text_content":"Prêt à ajouter l''IA à votre éditeur ?"}},{"block_type":"text","content":{"html_content":"<p class=\"text-center text-violet-100 max-w-xl mx-auto mt-2 mb-6\">Libérez la puissance de la création de contenu avec l''IA. Connectez votre clé, protégez vos données et rédigez vite.</p>"}},{"block_type":"button","content":{"url":"https://nextblock.dev/product/nextblock-cortex-ai-cortex-ai-license","size":"lg","text":"Acheter Cortex AI","variant":"secondary","position":"center"}}]],"container_type":"container","responsive_columns":{"mobile":1,"tablet":1,"desktop":1},"vertical_alignment":"center"}'::jsonb,
    updated_at = NOW()
WHERE id = 53;

-- Block ID 65
UPDATE public.blocks
SET content = '{"padding":{"top":"xl","bottom":"xl"},"background":{"type":"gradient","gradient":{"type":"linear","stops":[{"color":"#064e3b","position":0},{"color":"#0f172a","position":100}],"direction":"135deg"}},"column_gap":"xl","column_blocks":[[{"block_type":"text","content":{"html_content":"<p class=\"text-xs uppercase tracking-[0.3em] text-emerald-400 font-semibold mb-4\">Enterprise E-Commerce Engine</p><h2 class=\"text-3xl sm:text-4xl font-extrabold text-white tracking-tight mb-4\">Turn Next.js Into a Global Storefront.</h2><p class=\"text-base text-slate-300 leading-relaxed\">Commerce Pro is a fast store engine built for NextBlock. It helps teams sell physical goods and digital downloads with ease. Everything runs on your own server with total data ownership and zero extra fees.</p>"}}],[{"block_type":"text","content":{"html_content":"<div class=\"rounded-2xl border border-emerald-700 bg-slate-950 p-6 shadow-xl sm:p-8\"><h3 class=\"text-lg font-bold text-white mb-4\">Why Teams Choose Commerce Pro</h3><ul class=\"space-y-3 text-sm text-slate-300\"><li class=\"flex items-start gap-3\"><span class=\"text-emerald-400 font-bold\">✓</span><span><strong>Multi-Currency Pricing</strong> — Live exchange rates, clear charm pricing, and automatic visitor country detection.</span></li><li class=\"flex items-start gap-3\"><span class=\"text-emerald-400 font-bold\">✓</span><span><strong>Simple Tax Rules</strong> — Native Stripe Tax support calculates local taxes automatically during checkout.</span></li><li class=\"flex items-start gap-3\"><span class=\"text-emerald-400 font-bold\">✓</span><span><strong>Hybrid Product Catalog</strong> — Sell physical goods with stock counts alongside digital software license keys.</span></li></ul></div>"}}]],"container_type":"container","responsive_columns":{"mobile":1,"tablet":1,"desktop":2},"vertical_alignment":"center"}'::jsonb,
    updated_at = NOW()
WHERE id = 65;

-- Block ID 67
UPDATE public.blocks
SET content = '{"padding":{"top":"lg","bottom":"lg"},"background":{"type":"solid","color":"transparent"},"column_gap":"lg","column_blocks":[[{"block_type":"text","content":{"html_content":"<div class=\"h-full rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition-colors hover:border-emerald-300 dark:border-slate-800 dark:bg-slate-900\"><div class=\"mb-4 flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-50 text-xl dark:bg-emerald-950\">💳</div><h4 class=\"text-lg font-bold text-foreground mb-2\">Headless Stripe Checkout</h4><p class=\"text-sm text-muted-foreground leading-relaxed\">Fast checkout flows for single or multiple items. Orders process automatically through secure webhooks with zero friction.</p></div>"}}],[{"block_type":"text","content":{"html_content":"<div class=\"h-full rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition-colors hover:border-emerald-300 dark:border-slate-800 dark:bg-slate-900\"><div class=\"mb-4 flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-50 text-xl dark:bg-emerald-950\">🔑</div><h4 class=\"text-lg font-bold text-foreground mb-2\">Freemius Digital Licensing</h4><p class=\"text-sm text-muted-foreground leading-relaxed\">Deliver software files, issue license keys, and manage SaaS free trials easily. Everything connects directly to Freemius.</p></div>"}}],[{"block_type":"text","content":{"html_content":"<div class=\"h-full rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition-colors hover:border-emerald-300 dark:border-slate-800 dark:bg-slate-900\"><div class=\"mb-4 flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-50 text-xl dark:bg-emerald-950\">🛍️</div><h4 class=\"text-lg font-bold text-foreground mb-2\">Visual Merchandising</h4><p class=\"text-sm text-muted-foreground leading-relaxed\">Design custom product pages, highlight special deals, and build shopping grids right inside the visual block editor.</p></div>"}}]],"container_type":"container","responsive_columns":{"mobile":1,"tablet":2,"desktop":3},"vertical_alignment":"stretch"}'::jsonb,
    updated_at = NOW()
WHERE id = 67;

-- Block ID 68
UPDATE public.blocks
SET content = '{"padding":{"top":"xl","bottom":"xl"},"background":{"type":"gradient","gradient":{"type":"linear","stops":[{"color":"#0f172a","position":0},{"color":"#064e3b","position":100}],"direction":"135deg"}},"column_gap":"xl","column_blocks":[[{"block_type":"text","content":{"html_content":"<p class=\"text-xs uppercase tracking-[0.3em] text-emerald-400 font-semibold mb-4\">Under The Hood</p><h3 class=\"text-2xl font-bold text-white mb-4\">Built for Production Scale</h3><p class=\"text-sm text-slate-300 leading-relaxed mb-4\">Commerce Pro was built from day one for busy storefronts. Every API path is cached near your users, and database queries use fast indexes.</p><p class=\"text-sm text-slate-300 leading-relaxed\">Whether you sell digital downloads or retail goods, your storefront loads fast. It handles high traffic spikes without slow downs or crashes.</p>"}}],[{"block_type":"text","content":{"html_content":"<div class=\"space-y-4\"><div class=\"p-5 rounded-xl border border-slate-700 bg-slate-900\"><h4 class=\"text-sm font-bold text-white mb-1\">Order Management</h4><p class=\"text-xs text-slate-400 leading-relaxed\">Track customer orders from cart to shipping. Automatic status updates, buyer receipts, and refunds work right out of the box.</p></div><div class=\"p-5 rounded-xl border border-slate-700 bg-slate-900\"><h4 class=\"text-sm font-bold text-white mb-1\">Product Categories</h4><p class=\"text-xs text-slate-400 leading-relaxed\">Organize products with clean web addresses, category images, and full multi-language tags. Manage it all from the CMS dashboard.</p></div><div class=\"p-5 rounded-xl border border-slate-700 bg-slate-900\"><h4 class=\"text-sm font-bold text-white mb-1\">Multi-Language Storefronts</h4><p class=\"text-xs text-slate-400 leading-relaxed\">Translate products and category pages into any language. Each language shares inventory while keeping its own SEO metadata.</p></div></div>"}}]],"container_type":"container","responsive_columns":{"mobile":1,"tablet":1,"desktop":2},"vertical_alignment":"center"}'::jsonb,
    updated_at = NOW()
WHERE id = 68;

-- Block ID 69
UPDATE public.blocks
SET content = '{"padding":{"top":"xl","bottom":"xl"},"background":{"type":"gradient","gradient":{"type":"linear","stops":[{"color":"#064e3b","position":0},{"color":"#022c22","position":100}],"direction":"135deg"}},"column_gap":"none","column_blocks":[[{"block_type":"heading","content":{"level":2,"textAlign":"center","textColor":"background","text_content":"Ready to launch your storefront?"}},{"block_type":"text","content":{"html_content":"<p class=\"text-center text-emerald-100 max-w-xl mx-auto mt-2 mb-6\">Start selling today with Commerce Pro. It is multi-currency, tax-compliant, and lightning-fast out of the box.</p>"}},{"block_type":"button","content":{"url":"#","size":"lg","text":"Purchase Commerce Pro","variant":"secondary","position":"center"}}]],"container_type":"container","responsive_columns":{"mobile":1,"tablet":1,"desktop":1},"vertical_alignment":"center"}'::jsonb,
    updated_at = NOW()
WHERE id = 69;

-- Block ID 70
UPDATE public.blocks
SET content = '{"padding":{"top":"xl","bottom":"xl"},"background":{"type":"gradient","gradient":{"type":"linear","stops":[{"color":"#1e1b4b","position":0},{"color":"#0f172a","position":100}],"direction":"135deg"}},"column_gap":"xl","column_blocks":[[{"block_type":"text","content":{"html_content":"<p class=\"text-xs uppercase tracking-[0.3em] text-violet-400 font-semibold mb-4\">AI Intelligence Layer</p><h2 class=\"text-3xl sm:text-4xl font-extrabold text-white tracking-tight mb-4\">Supercharge Your Editor with AI.</h2><p class=\"text-base text-slate-300 leading-relaxed\">Cortex AI brings powerful language models directly into your editor. You can create content, edit blog drafts, and translate full pages in seconds. It writes clean block data rather than raw text, keeping your layouts stable and fast.</p>"}}],[{"block_type":"text","content":{"html_content":"<div class=\"rounded-2xl border border-violet-700 bg-slate-950 p-6 shadow-xl sm:p-8\"><h3 class=\"text-lg font-bold text-white mb-4\">OpenRouter &amp; BYOK Architecture</h3><ul class=\"space-y-3 text-sm text-slate-300\"><li class=\"flex items-start gap-3\"><span class=\"text-violet-400 font-bold\">✓</span><span><strong>Bring Your Own Key</strong> — You control costs using your own OpenRouter tokens. There are no hidden fees or markups.</span></li><li class=\"flex items-start gap-3\"><span class=\"text-violet-400 font-bold\">✓</span><span><strong>Block-Aware Prompts</strong> — Models receive structured context. They see headings, columns, and layout rules for accurate outputs.</span></li><li class=\"flex items-start gap-3\"><span class=\"text-violet-400 font-bold\">✓</span><span><strong>Model Flexibility</strong> — Switch freely between Claude, GPT, and open-source models without changing code.</span></li></ul></div>"}}]],"container_type":"container","responsive_columns":{"mobile":1,"tablet":1,"desktop":2},"vertical_alignment":"center"}'::jsonb,
    updated_at = NOW()
WHERE id = 70;

-- Block ID 72
UPDATE public.blocks
SET content = '{"padding":{"top":"lg","bottom":"lg"},"background":{"type":"solid","color":"transparent"},"column_gap":"lg","column_blocks":[[{"block_type":"text","content":{"html_content":"<div class=\"h-full rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition-colors hover:border-violet-300 dark:border-slate-800 dark:bg-slate-900\"><div class=\"mb-4 flex h-10 w-10 items-center justify-center rounded-xl bg-violet-50 text-xl dark:bg-violet-950\">✍️</div><h4 class=\"text-lg font-bold text-foreground mb-2\">One-Click Copywriting</h4><p class=\"text-sm text-muted-foreground leading-relaxed\">Write blog posts, polish headlines, and craft calls to action. Cortex AI matches your brand voice and writes clear prose with ease.</p></div>"}}],[{"block_type":"text","content":{"html_content":"<div class=\"h-full rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition-colors hover:border-violet-300 dark:border-slate-800 dark:bg-slate-900\"><div class=\"mb-4 flex h-10 w-10 items-center justify-center rounded-xl bg-violet-50 text-xl dark:bg-violet-950\">🔄</div><h4 class=\"text-lg font-bold text-foreground mb-2\">Structure Refactoring</h4><p class=\"text-sm text-muted-foreground leading-relaxed\">Reorganize layout grids, split columns, and reorder sections. Cortex AI produces valid block schemas that render safely every time.</p></div>"}}],[{"block_type":"text","content":{"html_content":"<div class=\"h-full rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition-colors hover:border-violet-300 dark:border-slate-800 dark:bg-slate-900\"><div class=\"mb-4 flex h-10 w-10 items-center justify-center rounded-xl bg-violet-50 text-xl dark:bg-violet-950\">🌐</div><h4 class=\"text-lg font-bold text-foreground mb-2\">Automated Translation</h4><p class=\"text-sm text-muted-foreground leading-relaxed\">Translate entire pages between languages with one click. Cortex AI keeps your styles, nested sections, and media links intact.</p></div>"}}]],"container_type":"container","responsive_columns":{"mobile":1,"tablet":2,"desktop":3},"vertical_alignment":"stretch"}'::jsonb,
    updated_at = NOW()
WHERE id = 72;

-- Block ID 73
UPDATE public.blocks
SET content = '{"padding":{"top":"xl","bottom":"xl"},"background":{"type":"gradient","gradient":{"type":"linear","stops":[{"color":"#0f172a","position":0},{"color":"#1e1b4b","position":100}],"direction":"135deg"}},"column_gap":"xl","column_blocks":[[{"block_type":"text","content":{"html_content":"<p class=\"text-xs uppercase tracking-[0.3em] text-violet-400 font-semibold mb-4\">How It Works</p><h3 class=\"text-2xl font-bold text-white mb-4\">AI That Understands Blocks</h3><p class=\"text-sm text-slate-300 leading-relaxed mb-4\">Most AI tools only generate flat text strings. Cortex AI is built specifically for NextBlock editors. It reads your full page structure, column arrays, and style options.</p><p class=\"text-sm text-slate-300 leading-relaxed\">This deep connection prevents broken markup and invalid data. Your team gets clean results that look great on desktop and mobile screens right away.</p>"}}],[{"block_type":"text","content":{"html_content":"<div class=\"space-y-4\"><div class=\"p-5 rounded-xl border border-slate-700 bg-slate-900\"><h4 class=\"text-sm font-bold text-white mb-1\">Content Generation</h4><p class=\"text-xs text-slate-400 leading-relaxed\">Create engaging copy for marketing pages and help docs. The assistant follows your editorial style guide and produces clean text.</p></div><div class=\"p-5 rounded-xl border border-slate-700 bg-slate-900\"><h4 class=\"text-sm font-bold text-white mb-1\">SEO Optimization</h4><p class=\"text-xs text-slate-400 leading-relaxed\">Draft concise meta titles and meta descriptions automatically. Cortex AI checks keyword density and reading ease before you publish.</p></div><div class=\"p-5 rounded-xl border border-slate-700 bg-slate-900\"><h4 class=\"text-sm font-bold text-white mb-1\">Privacy-First Design</h4><p class=\"text-xs text-slate-400 leading-relaxed\">Your content goes directly to your chosen provider via private API keys. We never store, log, or train on your private data.</p></div></div>"}}]],"container_type":"container","responsive_columns":{"mobile":1,"tablet":1,"desktop":2},"vertical_alignment":"center"}'::jsonb,
    updated_at = NOW()
WHERE id = 73;

-- Block ID 74
UPDATE public.blocks
SET content = '{"padding":{"top":"xl","bottom":"xl"},"background":{"type":"gradient","gradient":{"type":"linear","stops":[{"color":"#312e81","position":0},{"color":"#1e1b4b","position":100}],"direction":"135deg"}},"column_gap":"none","column_blocks":[[{"block_type":"heading","content":{"level":2,"textAlign":"center","textColor":"background","text_content":"Ready to add AI to your editor?"}},{"block_type":"text","content":{"html_content":"<p class=\"text-center text-violet-100 max-w-xl mx-auto mt-2 mb-6\">Unlock the full power of AI-driven content creation. Connect your key, protect your privacy, and edit faster today.</p>"}},{"block_type":"button","content":{"url":"#","size":"lg","text":"Purchase Cortex AI","variant":"secondary","position":"center"}}]],"container_type":"container","responsive_columns":{"mobile":1,"tablet":1,"desktop":1},"vertical_alignment":"center"}'::jsonb,
    updated_at = NOW()
WHERE id = 74;

COMMIT;
