import { NextResponse } from 'next/server';

import {
  matchesCortexAiMcpEnvToken,
  parseBearerToken,
  readCortexAiMcpEnvToken,
} from '@nextblock-cms/cortex';

import { ensureEnvLicenseActivation } from '../../../../lib/packages/env-license';
import { getProvisioningStatus } from '../../../../lib/setup/provisioning';
import { provisionFirstAdmin } from '../../../../lib/setup/provision-admin';
import { collectReadinessReport } from '../../../../lib/setup/readiness-service';

/**
 * Headless first-boot: create the first administrator and activate the environment
 * license without a browser.
 *
 * This is what `create-nextblock --non-interactive` calls once the Docker stack reports
 * `dbReady`, with the name and email it collected on the command line. It does exactly
 * what the last step of the /setup wizard does (`provisionFirstAdmin`), so the two paths
 * cannot drift.
 *
 * Authorization: the caller must present the instance's MCP_BEARER_TOKEN. That token
 * was generated by the scaffold on the operator's own machine and lives only in the
 * project's env file, so holding it proves control of the install. The route answers
 * 404 when no environment token is configured at all — on such an install the browser
 * wizard is the only way in, and the route should not even look like an option.
 *
 * Idempotent: on an already-provisioned instance nothing is created; the license step
 * still runs so a key added to the environment later gets activated.
 */
export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

const JSON_HEADERS = { 'Cache-Control': 'no-store' } as const;

function json(body: Record<string, unknown>, status: number) {
  return NextResponse.json(body, { headers: JSON_HEADERS, status });
}

function readString(value: unknown, maxLength: number): string | null {
  return typeof value === 'string' && value.trim().length > 0 && value.length <= maxLength
    ? value.trim()
    : null;
}

/** Practical email check (the WHATWG form-validation pattern), not a full RFC 5322 parser. */
const EMAIL_PATTERN =
  /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)+$/;

export async function POST(request: Request) {
  const envToken = readCortexAiMcpEnvToken();

  if (!envToken) {
    return json({ error: 'Not found.', ok: false }, 404);
  }

  if (!matchesCortexAiMcpEnvToken(parseBearerToken(request.headers.get('authorization')), envToken)) {
    return NextResponse.json(
      { error: 'A valid MCP_BEARER_TOKEN bearer is required.', ok: false },
      { headers: { ...JSON_HEADERS, 'WWW-Authenticate': 'Bearer realm="NextBlock setup"' }, status: 401 }
    );
  }

  const body = (await request.json().catch(() => null)) as Record<string, unknown> | null;
  const admin =
    body && typeof body['admin'] === 'object' && body['admin'] !== null
      ? (body['admin'] as Record<string, unknown>)
      : null;

  const email = readString(admin?.['email'], 320)?.toLowerCase() ?? null;
  const fullName = readString(admin?.['fullName'], 120);
  const password = typeof admin?.['password'] === 'string' ? (admin['password'] as string) : null;

  if (!email || !EMAIL_PATTERN.test(email) || !fullName) {
    return json(
      { code: 'INVALID_ADMIN', error: 'admin.email (valid address) and admin.fullName are required.', ok: false },
      400
    );
  }

  if (!password || password.length < 8) {
    return json({ code: 'INVALID_ADMIN', error: 'admin.password must be at least 8 characters.', ok: false }, 400);
  }

  const provisioning = await getProvisioningStatus();

  if (!provisioning.configured) {
    return json({ code: 'NOT_CONFIGURED', error: 'Supabase is not configured on this instance.', ok: false }, 503);
  }

  let adminCreated = false;
  let userId: string | null = null;

  if (!provisioning.hasAdmin) {
    const result = await provisionFirstAdmin({ email, fullName, password });

    if (!result.ok) {
      const status =
        result.code === 'already_provisioned' || result.code === 'race_lost' || result.code === 'email_exists'
          ? 409
          : result.code === 'invalid_input'
            ? 400
            : 503;

      return json({ code: result.code.toUpperCase(), error: result.error, ok: false }, status);
    }

    adminCreated = true;
    userId = result.userId;
  }

  // Activate NEXTBLOCK_LICENSE_KEY now that an owner exists to register it to. `force`
  // bypasses the failure back-off: the operator just asked explicitly.
  const license = await ensureEnvLicenseActivation({ force: true, owner: { email, fullName } });
  const report = await collectReadinessReport();

  return json(
    {
      ...report,
      admin: { created: adminCreated, email, userId },
      // The forced attempt above is more informative than the report's cached read
      // (`activated` / `failed` + error, rather than a plain `active`).
      license: { ...report.license, env: license },
      ok: true,
    },
    200
  );
}
